CREATE TABLE Consent (
  consent_id SERIAL PRIMARY KEY,
  session_id INTEGER UNIQUE NOT NULL,
  has_consent BOOLEAN DEFAULT FALSE,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_withdrawn BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (session_id) REFERENCES CHAT_SESSION(session_id) ON DELETE CASCADE
);
